-- V18: Store community and collateral survey results on survey table
ALTER TABLE survey
    ADD COLUMN IF NOT EXISTS collateral_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS collateral_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS collateral_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS collateral_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS is_primary BOOLEAN,
    ADD COLUMN IF NOT EXISTS community_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS building VARCHAR(50),
    ADD COLUMN IF NOT EXISTS unit_name VARCHAR(50),
    ADD COLUMN IF NOT EXISTS door_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS building_area DECIMAL(14, 2),
    ADD COLUMN IF NOT EXISTS land_area DECIMAL(14, 2),
    ADD COLUMN IF NOT EXISTS actual_use VARCHAR(100),
    ADD COLUMN IF NOT EXISTS occupancy_status VARCHAR(100),
    ADD COLUMN IF NOT EXISTS decoration VARCHAR(100),
    ADD COLUMN IF NOT EXISTS orientation VARCHAR(50),
    ADD COLUMN IF NOT EXISTS current_floor VARCHAR(50),
    ADD COLUMN IF NOT EXISTS floor_count INT,
    ADD COLUMN IF NOT EXISTS indoor_height VARCHAR(50),
    ADD COLUMN IF NOT EXISTS build_year INT,
    ADD COLUMN IF NOT EXISTS completion_date DATE,
    ADD COLUMN IF NOT EXISTS space_layout TEXT,
    ADD COLUMN IF NOT EXISTS facilities_condition TEXT,
    ADD COLUMN IF NOT EXISTS maintenance_condition TEXT,
    ADD COLUMN IF NOT EXISTS surrounding_environment TEXT,
    ADD COLUMN IF NOT EXISTS parcel_shape TEXT,
    ADD COLUMN IF NOT EXISTS terrain TEXT,
    ADD COLUMN IF NOT EXISTS land_level TEXT,
    ADD COLUMN IF NOT EXISTS soil_condition TEXT,
    ADD COLUMN IF NOT EXISTS land_development_level TEXT,
    ADD COLUMN IF NOT EXISTS landscape TEXT,
    ADD COLUMN IF NOT EXISTS construction_land DECIMAL(14, 2),
    ADD COLUMN IF NOT EXISTS land_acquisition DECIMAL(14, 2),
    ADD COLUMN IF NOT EXISTS floor_area_ratio DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS above_ground_ratio DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS civil_defense_area DECIMAL(14, 2),
    ADD COLUMN IF NOT EXISTS underground_ratio DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS greening_rate DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS building_density DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS building_height DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS household_count INT,
    ADD COLUMN IF NOT EXISTS parking_count INT,
    ADD COLUMN IF NOT EXISTS parking_ratio DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS property_rights_years INT,
    ADD COLUMN IF NOT EXISTS land_use_years INT;
